name: Beta Prerelease

on:
  push:
    branches:
      - 'story/**'
      - 'feature/**'
      - 'release/**'

jobs:
  beta:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@letuscode'
          always-auth: true
      - run: npm install --no-audit --no-fund
      - name: Verify npm auth
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npm whoami || true
      - run: npm run build --if-present
      - name: Bump prerelease version (beta) without tagging
        shell: bash
        run: |
          CURRENT=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT"
          npm version prerelease --preid=beta --no-git-tag-version
          NEW=$(node -p "require('./package.json').version")
          echo "New version: $NEW"
      - name: Publish to npm (beta tag)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: npm publish --tag beta --provenance --access public
