name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm install --no-audit --no-fund
      - name: Lint commit messages
        run: |
          npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.sha }} --verbose
